version: '3'
services:
  mysql:
    container_name: mysql-container
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: springdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: spring_password
    ports:
      - "3307:3306"
    networks:
      - spring-mysql-network
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    image: spring-mysql-app:v1.0
    container_name: spring-app-container
    ports:
      - "8080:8080"
    build: .
    depends_on:
      - mysql
    networks:
      - spring-mysql-network
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: springdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: spring_password

networks:
  spring-mysql-network:
    driver: bridge

volumes:
  mysql-data:
